language: julia
os:
- linux
- osx
julia:
- 0.6
notifications:
  email: false
env:
  global:
    - secure: "X9PqiqF96g1jOeg1i3oHn+3nLv3eqAriBhfsLhQKa0GuSCAFhoow4rFv638lQQTzgQEbk0lAu2tOF/1p+R6wtqZWIb9ZlNCeczaztbMZZnVi9zVUtfXsN5LPm3sElJy0ZMR2b/YYbWV/MmSGuop+yA7Ylc1F+8BIN5XFKXBdtLVX3W+HyRa5VlJWlQ5TlMlB3HEKi8i2jbmQuzYy9Uk3FzEIjDYRTcZrq/eoZo52CJtctVRt9b4iCPqtV7k/3makyk+FIS7+ZFeiAGYhc0AY2z473fvsW2phFBEDg/uOyQ7gBRQi87SC8IHCmcGTzrsmvLBfK9fSz479zCpUwWOlff12dBGtsBCno8xaVpnSTLjTHp716+DbCoSDzBO9Rm2gcl0/ePKoGVyaS4d1SlbMb0Zi5qtT6h4/MBmrT54nhG8tT+FZ1Bu1cMTzhfgJe0GHaW3PGoImuEGuj8kbtgCasaa1dK1YcMLYSu6co+LBlQHorwXxyoDv1KYspjuUKtVAu6qgXG+VSATaOKEt9cEbESMUJQOGGBQdGAr7hmqVzdqkwDz4oJSwQPMKVYMz12n9OdRUzi5V/XP1vf+xzSNbYPjCHuYsUofzgpo7CLINCqiAId3hK3CZN7I0T8CcsM8/mhta9r1WWQaB4075GJIni12YKqj5/iZjbZDdGCsRDHw="
    - secure: "DxAjYsygPX3mi63Mlo/14S8mWfb6rCRRcoJr+5qZLFIXGQdYa1I9XyHSziFIu3SnjbhTy1tS25dRIFnGk5Wt7qvBIjfwsk57LLanaz0lOOXR8Sc04c4WPTCQnmU5pnROQOOc/fW1HPCqzFDrW+cTa5OcvGhhzBmq/oyxU1nlvhGhlcmBqqA07vNExqd+nh6BEOEbI5dKwvMx8ssyQ1EdyeleQGVUNiJ4IxcH7xlrUEKwuHtvIXXzPowvbTj3twDS84J8D6Uj5wIPsUU+F2hjLxgdlYvCGsIA28AUZjf+BDAu1Zwon9twQi6yb6JXnAwtFeME9apU6PLCsAtf/Zj3B/x0F1y+tA/vYKUlW6wdgnO0w0xYoqrLfuJa4O67URgw/mtWaGRDYO+Bw5v/ydjoSDSsBxVaKfzgdc/PKnFbk8Zhhr1iTHxzStMQgWvNdLTeXbYNvO9aMx47x0Fp0TG2p223FPp59cqBIBMU7Ya3RRLd5cIdGwehGHZJkci7g9snjJfU6tSJLk15ZZ+gAhpBoRqOqrVgSkIEJOyIdC91yrNXZjvXM7zmzakouiZO++LCZAX9ilBxoTdUss8EuSYPDM5v+cycQFDGkSqAkjjq1XnjA6x0EaqprHo5HvNblOktEF97BlCj/7t3XTNbLs8mWjVTFjnhwIi5EiW08qru04w="
matrix:
  allow_failures:
    - julia: nightly
